import Head from "next/head";
import { useState } from "react";
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';

export default function Home() {

  type calculated = number | string

  //Allows for date validation
dayjs.extend(customParseFormat);

//current date
const currentYear = dayjs().year();
const currentMonth = dayjs().month() + 1;
const currentDay = dayjs().date();

  //state
const [day, setDay] = useState("");
const [month, setMonth] = useState("");
const [year, setYear] = useState("");
const [calcYear, setCalcYear] = useState<calculated>("--")
const [calcMonth, setCalcMonth] = useState<calculated>("--")
const [calcDay, setCalcDay] = useState<calculated>("--")
const date = `${year}-${month}-${day}`;

const handleSubmit = () => {
  if(dayjs(date, "YYYY-M-D", true).isValid()){
    console.log("submit true")
    setCalcYear(currentYear - parseInt(year) + " years")
    setCalcMonth(Math.abs(currentMonth - parseInt(month)) + " months")
    setCalcDay(Math.abs(currentDay - parseInt(day)) + " days")
    console.log(calcYear, calcDay, calcMonth)
  } else {
    console.log("submit false")
  }
}

  return (
    <>
      <Head>
        <title>Age Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>
          <form onSubmit={(e) => {
            e.preventDefault();
            handleSubmit()
          }}>
            <label htmlFor="day">Day</label>
            <input id="day" type="number" placeholder="DD" value={day} onChange={(e)=> setDay(e.target.value)}/>
            <label htmlFor="month">Month</label>
            <input id="month" type="number" placeholder="MM" value={month} onChange={(e)=> setMonth(e.target.value)}/>
            <label htmlFor="year">Year</label>
            <input id="year" type="number" placeholder="YYYY" value={year} onChange={(e) => setYear(e.target.value)}/>
            <button type="submit">Submit</button>
          </form>
          <section>
            <p>{calcYear}</p>
            <p>{calcMonth}</p>
            <p>{calcDay}</p>
          </section>
        </div>
      </main>
    </>
  );
}
